--- 

language: php
env:
  - MAGENTO_VERSION=v1.7.0.2
before_install:
- mysql -e 'create database vf_magento'
- git clone https://github.com/EcomDev/MageCI.git
install:
- ROOT_DIR=$(pwd)
- mkdir $ROOT_DIR/magento
- composer install --dev --prefer-source
- composer require kylecannon/magento:$MAGENTO_VERSION
- MAGE_DIR=$ROOT_DIR/vendor/kylecannon/magento

before_script:
- ln -s $ROOT_DIR/app/design/frontend/base/default/layout/vf $MAGE_DIR/app/design/frontend/base/default/layout/vf
- ln -s $ROOT_DIR/app/design/frontend/base/default/template/vf $MAGE_DIR/app/design/frontend/base/default/template/vf
- ln -s $ROOT_DIR/app/design/adminhtml/default/default/template/vf $MAGE_DIR/app/design/adminhtml/default/default/template/vf
- cd $ROOT_DIR

script:
- vendor/bin/phpunit -c phpunit.travis.xml --testsuite="vfall"
services:
- mysql
php: 
- 5.3
- 5.4
